### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [rgchris/rebol-tmbundle#1]
@rgchris We would like to use your bundle to highlight Rebol code on GitHub but I don't know what licensing terms you're distributing it under.
Any chance you could pick one from here: http://choosealicense.com?

**Comment by rgchris** [comment]
Consider it under MIT license.

**Comment by pchaigno** [comment]
@rgchris Could you add a mention of this in the README or in a LICENSE file? Thanks :yellow_heart:
