### ISSUE TITLE
Use standard scope names

### ISSUE THREAD

**Issue by pchaigno** [rgchris/rebol-tmbundle#2]
As I said in #1, I would like to use this bundle to highlight Rebol code on GitHub.
Unfortunately, that will only be possible if you use the [standard scope names](http://manual.macromates.com/en/language_grammars#naming_conventions). For instance, [this scope name](https://github.com/rgchris/rebol-tmbundle/blob/master/Syntaxes/Rebol.tmLanguage#L702) is nonstandard.

See github/linguist#2036 for more information.

**Comment by arfon** [comment]
:+1:

**Comment by pchaigno** [comment]
@rgchris Did you get a chance to look into this?

**Comment by rgchris** [comment]
@pchaigno I haven't—I'm open to the idea and will look into what is required. The only concern I have is that the standard scope names appear to be misnomers (or at best inadequate) when applied to Rebol and would be misleading to anyone using scope names to analyse Rebol values. I can see areas where it can be immediately brought into line—I'll set aside some time to review these and see where I get.

**Comment by rgchris** [comment]
Updated scope names.

**Comment by rgchris** [comment]
https://github.com/rgchris/rebol-tmbundle/commit/839a7d4d1666ade5f5802fb66ebf788e2381562c
